apiVersion: apps/v1
kind: Deployment
metadata:
  name: mandelbrot-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: vladyslavtaran/mandelbrot-worker:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: worker
spec:
  selector:
    app: worker
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
